import Head from 'next/head'
import Basic_button from '../components/Basic_button/Basic_button'
import Julian from '../components/Julian/Julian'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Julian />
        <Basic_button />
      </main>

    </div>
  )
}
